version: '3.8'

services:
  web:
    build: ./docker/python
    volumes:
      - ./src:/home/app/web
      - static_volume:/home/app/microservice/static
    command: sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && echo yes | python manage.py collectstatic
      && gunicorn --bind 0.0.0.0:8000 chatty.wsgi"
    expose:
      - "8000"
    ports:
      - "8000:8000"
#    depends_on:
#      - db
#      - redis
#    networks:
#      - es-net
  db:
    image: postgres:11.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5432:5432"
  nginx:
    build: ./docker/nginx
    volumes:
      - static_volume:/home/app/microservice/static
    ports:
      - "80:8000"
    depends_on:
      - web
    links:
      - web
    networks:
      - es-net
    restart: always
#  elasticsearch:
#    container_name: es-container
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
#    environment:
#      - xpack.security.enabled=false
#      - "discovery.type=single-node"
#    networks:
#      - es-net
#    ports:
#      - 9200:9200
#  redis:
#    container_name: redis
#    restart: always
#    image: redis:5
#    networks:
#      - es-net
#    ports:
#      - "6379:6379"
volumes:
  postgres_data:
  static_volume:
networks:
  es-net:
    driver: bridge
