version: "3.0"
services:
  chat:
    build: .
    command: sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && echo yes | python manage.py collectstatic
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - '../src:/var/www/html/'
    networks:
      - es-net
    ports:
      - "8000:8000"
    restart: always
#    depends_on:
#      - elasticsearch
#  elasticsearch:
#    container_name: es-container
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
#    environment:
#      - xpack.security.enabled=false
#      - "discovery.type=single-node"
#    networks:
#      - es-net
#    ports:
#      - 9200:9200
  redis:
    hostname: redis
    container_name: redis
    restart: always
    image: redis:5
    networks:
      - es-net
    ports:
      - "6379:6379"
#  kibana:
#    container_name: kb-container
#    image: docker.elastic.co/kibana/kibana:7.11.0
#    environment:
#      - ELASTICSEARCH_HOSTS=http://es-container:9200
#    networks:
#      - es-net
#    depends_on:
#      - elasticsearch
#    ports:
#      - 5601:5601
networks:
  es-net:
    driver: bridge